# Generated by Django 5.2.17 on 2026-09-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='additional_document',
            field=models.FileField(blank=True, null=True, upload_to='technician_documents/'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='admin_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='technician_documents/'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='professional_document',
            field=models.FileField(blank=True, null=True, upload_to='technician_documents/'),
        ),
    ]
